# Generated by Django 5.2.6 on 2025-09-26 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_plan', models.CharField(max_length=100, verbose_name='Тарифный план')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='MediaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
                ('country', models.CharField(max_length=100, verbose_name='Страна производства')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('age_restriction', models.PositiveIntegerField(verbose_name='Возрастное ограничение')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность')),
                ('content_type', models.CharField(choices=[('MOVIE', 'Фильм'), ('SERIES', 'Сериал')], max_length=10, verbose_name='Тип')),
                ('genres', models.ManyToManyField(to='kf_app.genre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Медиаконтент',
                'verbose_name_plural': 'Медиаконтент',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kf_app.mediacontent', verbose_name='Медиаконтент')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
            },
        ),
        migrations.CreateModel(
            name='ContentParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100, verbose_name='Роль')),
                ('role_name', models.CharField(max_length=100, verbose_name='Название роли')),
                ('media_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kf_app.mediacontent', verbose_name='Медиаконтент')),
            ],
            options={
                'verbose_name': 'Участие в контенте',
                'verbose_name_plural': 'Участие в контенте',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('biography', models.TextField(verbose_name='Биография')),
                ('media_content', models.ManyToManyField(through='kf_app.ContentParticipation', to='kf_app.mediacontent', verbose_name='Участие в контенте')),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персоны',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='contentparticipation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kf_app.person', verbose_name='Персона'),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField(verbose_name='Номер сезона')),
                ('title', models.CharField(max_length=255, verbose_name='Название сезона')),
                ('description', models.TextField(verbose_name='Описание')),
                ('media_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kf_app.mediacontent', verbose_name='Медиаконтент')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveIntegerField(verbose_name='Номер эпизода')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность')),
                ('release_date', models.DateField(verbose_name='Дата выхода эпизода')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kf_app.season', verbose_name='Сезон')),
            ],
            options={
                'verbose_name': 'Эпизод',
                'verbose_name_plural': 'Эпизоды',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='Почта')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('favorites', models.ManyToManyField(through='kf_app.Favorite', to='kf_app.mediacontent', verbose_name='Избранное')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Оценка')),
                ('review_text', models.TextField(verbose_name='Текст отзыва')),
                ('media_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kf_app.mediacontent', verbose_name='Медиаконтент')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kf_app.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kf_app.user', verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Активна'), ('EXPIRED', 'Истекла'), ('CANCELED', 'Отменена')], max_length=10, verbose_name='Статус подписки')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('auto_renewal', models.BooleanField(default=False, verbose_name='Автопродление')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Способ оплаты')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kf_app.subscription', verbose_name='Подписка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kf_app.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка пользователя',
                'verbose_name_plural': 'Подписки пользователей',
            },
        ),
        migrations.CreateModel(
            name='ViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(verbose_name='Дата и время просмотра')),
                ('viewed_seconds', models.PositiveIntegerField(verbose_name='Просмотрено секунд')),
                ('media_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kf_app.mediacontent', verbose_name='Медиаконтент')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kf_app.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История просмотров',
                'verbose_name_plural': 'История просмотров',
            },
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('media_content', 'season_number'), name='unique_media_season'),
        ),
        migrations.AddConstraint(
            model_name='episode',
            constraint=models.UniqueConstraint(fields=('season', 'episode_number'), name='unique_season_episode'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'media_content'), name='unique_user_media_review'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'media_content'), name='unique_user_media_favorite'),
        ),
    ]
