# Generated by Django 5.2.6 on 2025-09-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kf_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='dessc',
            field=models.CharField(default='No', verbose_name='Жив или нет'),
        ),
    ]
