# Generated by Django 5.2.6 on 2025-09-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kf_app', '0002_author_dessc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['surname', 'name'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['surname'], name='kf_app_auth_surname_43f910_idx'),
        ),
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(condition=models.Q(('dessc', 'Жив')), fields=('surname', 'bio'), name='unique_surname_bio'),
        ),
    ]
